# Generated by Django 3.2.10 on 2021-12-22 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('line_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Person', to='Demo.person')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Employee', to='Demo.person')),
            ],
        ),
    ]
